local Constants = {};

local iota do
    local next = 1;

    function iota()
        local value = next;
        next = next + 1;
        return value;
    end
end

Constants.IconCategory = setmetatable({
    Untagged = iota(),
    Ability = iota(),
    Item = iota(),
    Warrior = iota(),
    Paladin = iota(),
    Hunter = iota(),
    Rogue = iota(),
    Priest = iota(),
    DeathKnight = iota(),
    Shaman = iota(),
    Mage = iota(),
    Warlock = iota(),
    Monk = iota(),
    Druid = iota(),
    DemonHunter = iota(),
    Evoker = iota(),
    Equipment = iota(),
    Weapon = iota(),
    MeleeWeapon = iota(),
    Axe = iota(),
    Dagger = iota(),
    Mace = iota(),
    Polearm = iota(),
    Staff = iota(),
    Sword = iota(),
    FistWeapon = iota(),
    Warglaive = iota(),
    RangedWeapon = iota(),
    Ammo = iota(),
    Bow = iota(),
    Crossbow = iota(),
    Gun = iota(),
    Thrown = iota(),
    Wand = iota(),
    OffHand = iota(),
    Shield = iota(),
    Armor = iota(),
    ClothArmor = iota(),
    LeatherArmor = iota(),
    MailArmor = iota(),
    PlateArmor = iota(),
    Back = iota(),
    Chest = iota(),
    Feet = iota(),
    Hands = iota(),
    Head = iota(),
    Legs = iota(),
    Shirt = iota(),
    Shoulder = iota(),
    Tabard = iota(),
    Waist = iota(),
    Wrist = iota(),
    Jewelry = iota(),
    Necklace = iota(),
    Ring = iota(),
    Trinket = iota(),
    Physical = iota(),
    Magic = iota(),
    Arcane = iota(),
    Fire = iota(),
    Frost = iota(),
    Holy = iota(),
    Nature = iota(),
    Shadow = iota(),
    Faction = iota(),
    Alliance = iota(),
    Horde = iota(),
    Mount = iota(),
    Pet = iota(),
    Achievement = iota(),
    Potion = iota(),
    Food = iota(),
    Drink = iota(),
    TradeGoods = iota(),
    Professions = iota(),
    Alchemy = iota(),
    Archaeology = iota(),
    Blacksmithing = iota(),
    Cooking = iota(),
    Enchanting = iota(),
    Engineering = iota(),
    FirstAid = iota(),
    Herbalism = iota(),
    Inscription = iota(),
    Jewelcrafting = iota(),
    Leatherworking = iota(),
    Mining = iota(),
    Skinning = iota(),
    Tailoring = iota(),
    Fishing = iota(),
    Housing = iota(),
    HousingDye = iota(),
    Garrisons = iota(),
    Human = iota(),
    Dwarf = iota(),
    NightElf = iota(),
    Gnome = iota(),
    Draenei = iota(),
    Worgen = iota(),
    Orc = iota(),
    Undead = iota(),
    Tauren = iota(),
    Troll = iota(),
    BloodElf = iota(),
    Goblin = iota(),
    Pandaren = iota(),
    Dracthyr = iota(),
    VoidElf = iota(),
    LightforgedDraenei = iota(),
    DarkIronDwarf = iota(),
    KulTiran = iota(),
    Mechagnome = iota(),
    Earthen = iota(),
    Nightborne = iota(),
    HighmountainTauren = iota(),
    MagharOrc = iota(),
    ZandalariTroll = iota(),
    Vulpera = iota(),
    Haranir = iota(),
    Fel = iota(),
    Void = iota(),
}, { __index = function(_, k) error("unknown category: " .. k); end });

Constants.IconCategoryParents = {
    [Constants.IconCategory.Weapon] = Constants.IconCategory.Equipment,
    [Constants.IconCategory.MeleeWeapon] = Constants.IconCategory.Weapon,
    [Constants.IconCategory.Axe] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.Dagger] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.Mace] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.Polearm] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.Staff] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.Sword] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.FistWeapon] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.Warglaive] = Constants.IconCategory.MeleeWeapon,
    [Constants.IconCategory.RangedWeapon] = Constants.IconCategory.Weapon,
    [Constants.IconCategory.Ammo] = Constants.IconCategory.RangedWeapon,
    [Constants.IconCategory.Bow] = Constants.IconCategory.RangedWeapon,
    [Constants.IconCategory.Crossbow] = Constants.IconCategory.RangedWeapon,
    [Constants.IconCategory.Gun] = Constants.IconCategory.RangedWeapon,
    [Constants.IconCategory.Thrown] = Constants.IconCategory.RangedWeapon,
    [Constants.IconCategory.Wand] = Constants.IconCategory.RangedWeapon,
    [Constants.IconCategory.OffHand] = Constants.IconCategory.Weapon,
    [Constants.IconCategory.Shield] = Constants.IconCategory.Weapon,
    [Constants.IconCategory.Arcane] = Constants.IconCategory.Magic,
    [Constants.IconCategory.Fire] = Constants.IconCategory.Magic,
    [Constants.IconCategory.Frost] = Constants.IconCategory.Magic,
    [Constants.IconCategory.Holy] = Constants.IconCategory.Magic,
    [Constants.IconCategory.Nature] = Constants.IconCategory.Magic,
    [Constants.IconCategory.Shadow] = Constants.IconCategory.Magic,
    [Constants.IconCategory.Armor] = Constants.IconCategory.Equipment,
    [Constants.IconCategory.ClothArmor] = Constants.IconCategory.Armor,
    [Constants.IconCategory.LeatherArmor] = Constants.IconCategory.Armor,
    [Constants.IconCategory.MailArmor] = Constants.IconCategory.Armor,
    [Constants.IconCategory.PlateArmor] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Back] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Chest] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Feet] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Hands] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Head] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Legs] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Shirt] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Shoulder] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Tabard] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Waist] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Wrist] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Jewelry] = Constants.IconCategory.Armor,
    [Constants.IconCategory.Necklace] = Constants.IconCategory.Jewelry,
    [Constants.IconCategory.Ring] = Constants.IconCategory.Jewelry,
    [Constants.IconCategory.Trinket] = Constants.IconCategory.Jewelry,
    [Constants.IconCategory.Alliance] = Constants.IconCategory.Faction,
    [Constants.IconCategory.Horde] = Constants.IconCategory.Faction,
    [Constants.IconCategory.Potion] = Constants.IconCategory.Item,
    [Constants.IconCategory.Food] = Constants.IconCategory.Item,
    [Constants.IconCategory.Drink] = Constants.IconCategory.Item,
    [Constants.IconCategory.TradeGoods] = Constants.IconCategory.Item,
    [Constants.IconCategory.Alchemy] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Archaeology] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Blacksmithing] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Cooking] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Engineering] = Constants.IconCategory.Professions,
    [Constants.IconCategory.FirstAid] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Herbalism] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Inscription] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Jewelcrafting] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Leatherworking] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Mining] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Skinning] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Tailoring] = Constants.IconCategory.Professions,
    [Constants.IconCategory.Fishing] = Constants.IconCategory.Professions,
    [Constants.IconCategory.HousingDye] = Constants.IconCategory.Housing,
    [Constants.IconCategory.LightforgedDraenei] = Constants.IconCategory.Draenei,
    [Constants.IconCategory.DarkIronDwarf] = Constants.IconCategory.Dwarf,
    [Constants.IconCategory.KulTiran] = Constants.IconCategory.Human,
    [Constants.IconCategory.Mechagnome] = Constants.IconCategory.Gnome,
    [Constants.IconCategory.Earthen] = Constants.IconCategory.Dwarf,
    [Constants.IconCategory.HighmountainTauren] = Constants.IconCategory.Tauren,
    [Constants.IconCategory.MagharOrc] = Constants.IconCategory.Orc,
    [Constants.IconCategory.ZandalariTroll] = Constants.IconCategory.Troll,
};

local function Prefix(word)
    return "^" .. word;
end

local function Suffix(word)  -- luacheck: no unused
    return word .. "$";
end

local function Substring(str)
    return ".*" .. str .. ".*";
end

local function Word(word)
    return "%f[%w]" .. word .. "%f[%W]";
end

local function WordStart(ste)
    return "%f[%w]" .. ste;
end

local function WordEnd(str)
    return str .. "%f[%W]";
end

Constants.IconCategoryPatterns = {
    -- Misc.
    { include = { Prefix "ability" }, tags = { Constants.IconCategory.Ability } },
    { include = { Prefix "achieve?ment" }, tags = { Constants.IconCategory.Achievement } },
    { include = { Prefix "inv_ability" }, tags = { Constants.IconCategory.Ability } },
    { include = { Prefix "inv_spell" }, tags = { Constants.IconCategory.Ability } },
    { include = { Prefix "inv" }, exclude = { Word "ability", Word "spell" }, tags = { Constants.IconCategory.Item } },
    { include = { Prefix "inv", Word "drink" }, tags = { Constants.IconCategory.Drink } },
    { include = { Prefix "inv", Word "food" }, exclude = { Word "armor" }, tags = { Constants.IconCategory.Food } },
    { include = { Prefix "spell" }, tags = { Constants.IconCategory.Ability } },
    { include = { Substring "mount" }, tags = { Constants.IconCategory.Mount } },
    { include = { Word "bloodknightcharger" }, tags = { Constants.IconCategory.Mount } },
    { include = { Word "endeavor" }, tags = { Constants.IconCategory.Housing } },
    { include = { Word "garrisons?" }, tags = { Constants.IconCategory.Garrisons } },
    { include = { Word "homestone" }, tags = { Constants.IconCategory.Housing } },
    { include = { Word "house" }, tags = { Constants.IconCategory.Housing } },
    { include = { Word "housing" }, tags = { Constants.IconCategory.Housing } },
    { include = { Word "housing", Word "dye" }, tags = { Constants.IconCategory.HousingDye } },
    { include = { Word "item" }, tags = { Constants.IconCategory.Item } },
    { include = { Word "neighborhood" }, tags = { Constants.IconCategory.Housing } },
    { include = { Word "petfamily" }, tags = { Constants.IconCategory.Pet } },
    { include = { Word "raidability" }, tags = { Constants.IconCategory.Ability } },
    { include = { Word "ships" }, tags = { Constants.IconCategory.Garrisons } },
    { include = { Word "upgradestone" }, tags = { Constants.IconCategory.Pet } },
    { include = { WordEnd "pet" }, tags = { Constants.IconCategory.Pet } },
    { include = { WordStart "pet" }, tags = { Constants.IconCategory.Pet } },

    -- Armor
    { include = { Prefix "inv", Word "amulet" }, tags = { Constants.IconCategory.Necklace } },
    { include = { Prefix "inv", Word "armor" }, tags = { Constants.IconCategory.Armor } },
    { include = { Prefix "inv", Word "back" }, tags = { Constants.IconCategory.Back } },
    { include = { Prefix "inv", Word "back" }, tags = { Constants.IconCategory.Back } },
    { include = { Prefix "inv", Word "belt" }, tags = { Constants.IconCategory.Waist } },
    { include = { Prefix "inv", Word "boots?" }, tags = { Constants.IconCategory.Feet } },
    { include = { Prefix "inv", Word "bracer" }, tags = { Constants.IconCategory.Wrist } },
    { include = { Prefix "inv", Word "buckle" }, tags = { Constants.IconCategory.Waist } },
    { include = { Prefix "inv", Word "cape" }, tags = { Constants.IconCategory.Back } },
    { include = { Prefix "inv", Word "cape" }, tags = { Constants.IconCategory.Back } },
    { include = { Prefix "inv", Word "chest" }, tags = { Constants.IconCategory.Chest } },
    { include = { Prefix "inv", Word "cloak" }, tags = { Constants.IconCategory.Back } },
    { include = { Prefix "inv", Word "cloth" }, tags = { Constants.IconCategory.ClothArmor } },
    { include = { Prefix "inv", Word "gauntlets?" }, exclude = { Word "weapon" }, tags = { Constants.IconCategory.Hands } },
    { include = { Prefix "inv", Word "gloves?" }, exclude = { Word "weapon" }, tags = { Constants.IconCategory.Hands } },
    { include = { Prefix "inv", Word "hands?" }, exclude = { Word "weapon" }, tags = { Constants.IconCategory.Hands } },
    { include = { Prefix "inv", Word "head" }, tags = { Constants.IconCategory.Head } },
    { include = { Prefix "inv", Word "helm" }, tags = { Constants.IconCategory.Head } },
    { include = { Prefix "inv", Word "helmet" }, tags = { Constants.IconCategory.Head } },
    { include = { Prefix "inv", Word "jewelry" }, tags = { Constants.IconCategory.Jewelry } },
    { include = { Prefix "inv", Word "jewelrytrinkets?" }, tags = { Constants.IconCategory.Trinket } },
    { include = { Prefix "inv", Word "leather" }, tags = { Constants.IconCategory.LeatherArmor } },
    { include = { Prefix "inv", Word "mace" }, tags = { Constants.IconCategory.Mace } },
    { include = { Prefix "inv", Word "mail" }, tags = { Constants.IconCategory.MailArmor } },
    { include = { Prefix "inv", Word "necklace" }, tags = { Constants.IconCategory.Necklace } },
    { include = { Prefix "inv", Word "offhand" }, tags = { Constants.IconCategory.OffHand } },
    { include = { Prefix "inv", Word "pants?" }, tags = { Constants.IconCategory.Legs } },
    { include = { Prefix "inv", Word "plate" }, tags = { Constants.IconCategory.PlateArmor } },
    { include = { Prefix "inv", Word "ring" }, tags = { Constants.IconCategory.Ring } },
    { include = { Prefix "inv", Word "robe" }, tags = { Constants.IconCategory.Chest } },
    { include = { Prefix "inv", Word "shirt" }, tags = { Constants.IconCategory.Shirt } },
    { include = { Prefix "inv", Word "shoulder" }, tags = { Constants.IconCategory.Shoulder } },
    { include = { Prefix "inv", Word "tabard" }, tags = { Constants.IconCategory.Tabard } },
    { include = { Prefix "inv", Word "trinket" }, tags = { Constants.IconCategory.Trinket } },
    { include = { Word "buckle", Word "armor" }, tags = { Constants.IconCategory.Waist } },

    -- Weapons
    { include = { Prefix "inv", Word "arrow" }, tags = { Constants.IconCategory.Ammo } },
    { include = { Prefix "inv", Word "axe" }, tags = { Constants.IconCategory.Axe } },
    { include = { Prefix "inv", Word "bow" }, tags = { Constants.IconCategory.Bow } },
    { include = { Prefix "inv", Word "bullet" }, tags = { Constants.IconCategory.Ammo } },
    { include = { Prefix "inv", Word "chakr[au]m" }, tags = { Constants.IconCategory.Thrown } },
    { include = { Prefix "inv", Word "crossbow" }, tags = { Constants.IconCategory.Crossbow } },
    { include = { Prefix "inv", Word "dagger" }, tags = { Constants.IconCategory.Dagger } },
    { include = { Prefix "inv", Word "firearm" }, tags = { Constants.IconCategory.Gun } },
    { include = { Prefix "inv", Word "flail" }, tags = { Constants.IconCategory.Mace } },
    { include = { Prefix "inv", Word "gauntlets?", Word "weapon" }, tags = { Constants.IconCategory.FistWeapon } },
    { include = { Prefix "inv", Word "glaive" }, tags = { Constants.IconCategory.Sword, Constants.IconCategory.Warglaive } },
    { include = { Prefix "inv", Word "gloves?", Word "weapon" }, tags = { Constants.IconCategory.FistWeapon } },
    { include = { Prefix "inv", Word "gun" }, tags = { Constants.IconCategory.Gun } },
    { include = { Prefix "inv", Word "halberd" }, tags = { Constants.IconCategory.Polearm } },
    { include = { Prefix "inv", Word "hands?", Word "weapon" }, tags = { Constants.IconCategory.FistWeapon } },
    { include = { Prefix "inv", Word "knife" }, tags = { Constants.IconCategory.Dagger } },
    { include = { Prefix "inv", Word "pike" }, tags = { Constants.IconCategory.Polearm } },
    { include = { Prefix "inv", Word "polearm" }, tags = { Constants.IconCategory.Polearm } },
    { include = { Prefix "inv", Word "rifle" }, tags = { Constants.IconCategory.Gun } },
    { include = { Prefix "inv", Word "shield" }, tags = { Constants.IconCategory.Shield } },
    { include = { Prefix "inv", Word "shortblade" }, tags = { Constants.IconCategory.Sword } },
    { include = { Prefix "inv", Word "staff" }, tags = { Constants.IconCategory.Staff } },
    { include = { Prefix "inv", Word "stave" }, tags = { Constants.IconCategory.Staff } },
    { include = { Prefix "inv", Word "sword" }, tags = { Constants.IconCategory.Sword } },
    { include = { Prefix "inv", Word "throwingaxe" }, tags = { Constants.IconCategory.Thrown } },
    { include = { Prefix "inv", Word "throwingknife" }, tags = { Constants.IconCategory.Thrown } },
    { include = { Prefix "inv", Word "thrown" }, tags = { Constants.IconCategory.Thrown } },
    { include = { Prefix "inv", Word "wand" }, tags = { Constants.IconCategory.Wand } },
    { include = { Prefix "inv", Word "warglaive" }, tags = { Constants.IconCategory.Sword, Constants.IconCategory.Warglaive } },
    { include = { Prefix "inv", Word "weapon" }, tags = { Constants.IconCategory.Weapon } },
    { include = { Word "axe", Word "[12]h" }, tags = { Constants.IconCategory.Axe } },
    { include = { Word "bow", Word "[12]h" }, tags = { Constants.IconCategory.Bow } },
    { include = { Word "crossbow", Word "[12]h" }, tags = { Constants.IconCategory.Crossbow } },
    { include = { Word "dagger", Word "[12]h" }, tags = { Constants.IconCategory.Dagger } },
    { include = { Word "firearm", Word "[12]h" }, tags = { Constants.IconCategory.Gun } },
    { include = { Word "glaive", Word "[12]h" }, tags = { Constants.IconCategory.Sword, Constants.IconCategory.Warglaive } },
    { include = { Word "gun", Word "[12]h" }, tags = { Constants.IconCategory.Gun } },
    { include = { Word "halberd", Word "[12]h" }, tags = { Constants.IconCategory.Polearm } },
    { include = { Word "knife", Word "[12]h" }, tags = { Constants.IconCategory.Dagger } },
    { include = { Word "polearm", Word "[12]h" }, tags = { Constants.IconCategory.Polearm } },
    { include = { Word "rifle", Word "[12]h" }, tags = { Constants.IconCategory.Gun } },
    { include = { Word "shield", Word "[12]h" }, tags = { Constants.IconCategory.Shield } },
    { include = { Word "staff", Word "[12]h" }, tags = { Constants.IconCategory.Staff } },
    { include = { Word "stave", Word "tarecgosa" }, tags = { Constants.IconCategory.Staff } },
    { include = { Word "sword", Word "[12]h" }, tags = { Constants.IconCategory.Sword } },
    { include = { Word "wand", Word "[12]h" }, tags = { Constants.IconCategory.Wand } },
    { include = { Word "warglaive", Word "[12]h" }, tags = { Constants.IconCategory.Sword, Constants.IconCategory.Warglaive } },

    -- Races
    { include = { Substring "bloodknight" }, tags = { Constants.IconCategory.BloodElf } },
    { include = { Word "bloodelf" }, tags = { Constants.IconCategory.BloodElf } },
    { include = { Word "darkiron" }, tags = { Constants.IconCategory.DarkIronDwarf } },
    { include = { Word "darkirondwarf" }, tags = { Constants.IconCategory.DarkIronDwarf } },
    { include = { Word "dracthyr" }, tags = { Constants.IconCategory.Dracthyr } },
    { include = { Word "draenei" }, tags = { Constants.IconCategory.Draenei } },
    { include = { Word "dwarf" }, tags = { Constants.IconCategory.Dwarf } },
    { include = { Word "earthen" }, tags = { Constants.IconCategory.Earthen } },
    { include = { Word "gnome" }, tags = { Constants.IconCategory.Gnome } },
    { include = { Word "goblin" }, tags = { Constants.IconCategory.Goblin } },
    { include = { Word "haranir" }, tags = { Constants.IconCategory.Haranir } },
    { include = { Word "harronir" }, tags = { Constants.IconCategory.Haranir } },
    { include = { Word "highmountain" }, tags = { Constants.IconCategory.HighmountainTauren } },
    { include = { Word "highmountaintauren" }, tags = { Constants.IconCategory.HighmountainTauren } },
    { include = { Word "human" }, tags = { Constants.IconCategory.Human } },
    { include = { Word "kultiran" }, tags = { Constants.IconCategory.KulTiran } },
    { include = { Word "kultiras" }, tags = { Constants.IconCategory.KulTiran } },
    { include = { Word "lightforged" }, tags = { Constants.IconCategory.LightforgedDraenei } },
    { include = { Word "lightforgeddraenei" }, tags = { Constants.IconCategory.LightforgedDraenei } },
    { include = { Word "maghar" }, tags = { Constants.IconCategory.MagharOrc } },
    { include = { Word "magharorc" }, tags = { Constants.IconCategory.MagharOrc } },
    { include = { Word "mechagnome" }, tags = { Constants.IconCategory.Mechagnome } },
    { include = { Word "nightborne?" }, tags = { Constants.IconCategory.Nightborne } },
    { include = { Word "nightelf" }, tags = { Constants.IconCategory.NightElf } },
    { include = { Word "orc" }, tags = { Constants.IconCategory.Orc } },
    { include = { Word "pandaren" }, tags = { Constants.IconCategory.Pandaren } },
    { include = { Word "pandaria" }, tags = { Constants.IconCategory.Pandaren } },
    { include = { Word "tauren" }, tags = { Constants.IconCategory.Tauren } },
    { include = { Word "troll" }, tags = { Constants.IconCategory.Troll } },
    { include = { Word "undead" }, tags = { Constants.IconCategory.Undead } },
    { include = { Word "voidelf" }, tags = { Constants.IconCategory.VoidElf } },
    { include = { Word "vulpera" }, tags = { Constants.IconCategory.Vulpera } },
    { include = { Word "worgen" }, tags = { Constants.IconCategory.Worgen } },
    { include = { Word "zandalari" }, tags = { Constants.IconCategory.ZandalariTroll } },
    { include = { Word "zandalaritroll" }, tags = { Constants.IconCategory.ZandalariTroll } },

    -- Racials
    { include = { Prefix "pandarenracial" }, tags = { Constants.IconCategory.Ability, Constants.IconCategory.Pandaren } },

    -- Classes
    { include = { Word "deathknight" }, tags = { Constants.IconCategory.DeathKnight } },
    { include = { Word "demonhunter" }, tags = { Constants.IconCategory.DemonHunter } },
    { include = { Word "druid" }, tags = { Constants.IconCategory.Druid } },
    { include = { Word "evoker" }, tags = { Constants.IconCategory.Evoker } },
    { include = { Word "hunter" }, tags = { Constants.IconCategory.Hunter } },
    { include = { Word "mage" }, tags = { Constants.IconCategory.Mage } },
    { include = { Word "monk" }, tags = { Constants.IconCategory.Monk } },
    { include = { Word "paladin" }, tags = { Constants.IconCategory.Paladin } },
    { include = { Word "priest" }, tags = { Constants.IconCategory.Priest } },
    { include = { Word "rogue" }, tags = { Constants.IconCategory.Rogue } },
    { include = { Word "shaman" }, tags = { Constants.IconCategory.Shaman } },
    { include = { Word "warlock" }, tags = { Constants.IconCategory.Warlock } },
    { include = { Word "warrior" }, tags = { Constants.IconCategory.Warrior } },

    -- Class Equipment
    { include = { Prefix "inv", Substring "deathknight" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DeathKnight } },
    { include = { Prefix "inv", Substring "demonhunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DemonHunter } },
    { include = { Prefix "inv", Substring "druid" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Druid } },
    { include = { Prefix "inv", Substring "evoker" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Evoker } },
    { include = { Prefix "inv", Substring "hunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Hunter } },
    { include = { Prefix "inv", Substring "mage" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Mage } },
    { include = { Prefix "inv", Substring "monk" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Monk } },
    { include = { Prefix "inv", Substring "paladin" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Paladin } },
    { include = { Prefix "inv", Substring "priest" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Priest } },
    { include = { Prefix "inv", Substring "rogue" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Rogue } },
    { include = { Prefix "inv", Substring "shaman" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Shaman } },
    { include = { Prefix "inv", Substring "warlock" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warlock } },
    { include = { Prefix "inv", Substring "warrior" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warrior } },
    { include = { Substring "dungeondeathknight" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DeathKnight } },
    { include = { Substring "dungeondemonhunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DemonHunter } },
    { include = { Substring "dungeondruid" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Druid } },
    { include = { Substring "dungeonevoker" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Evoker } },
    { include = { Substring "dungeonhunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Hunter } },
    { include = { Substring "dungeonmage" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Mage } },
    { include = { Substring "dungeonmonk" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Monk } },
    { include = { Substring "dungeonpaladin" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Paladin } },
    { include = { Substring "dungeonpriest" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Priest } },
    { include = { Substring "dungeonrogue" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Rogue } },
    { include = { Substring "dungeonshaman" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Shaman } },
    { include = { Substring "dungeonwarlock" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warlock } },
    { include = { Substring "dungeonwarrior" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warrior } },
    { include = { Substring "pvpdeathknight" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DeathKnight } },
    { include = { Substring "pvpdemonhunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DemonHunter } },
    { include = { Substring "pvpdruid" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Druid } },
    { include = { Substring "pvpevoker" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Evoker } },
    { include = { Substring "pvphunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Hunter } },
    { include = { Substring "pvpmage" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Mage } },
    { include = { Substring "pvpmonk" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Monk } },
    { include = { Substring "pvppaladin" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Paladin } },
    { include = { Substring "pvppriest" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Priest } },
    { include = { Substring "pvprogue" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Rogue } },
    { include = { Substring "pvpshaman" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Shaman } },
    { include = { Substring "pvpwarlock" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warlock } },
    { include = { Substring "pvpwarrior" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warrior } },
    { include = { Substring "raiddeathknight" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DeathKnight } },
    { include = { Substring "raiddemonhunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.DemonHunter } },
    { include = { Substring "raiddruid" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Druid } },
    { include = { Substring "raidevoker" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Evoker } },
    { include = { Substring "raidhunter" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Hunter } },
    { include = { Substring "raidmage" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Mage } },
    { include = { Substring "raidmonk" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Monk } },
    { include = { Substring "raidpaladin" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Paladin } },
    { include = { Substring "raidpriest" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Priest } },
    { include = { Substring "raidrogue" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Rogue } },
    { include = { Substring "raidshaman" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Shaman } },
    { include = { Substring "raidwarlock" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warlock } },
    { include = { Substring "raidwarrior" }, tags = { Constants.IconCategory.Equipment, Constants.IconCategory.Warrior } },
    { include = { Word "armor", Substring "deathknight" }, tags = { Constants.IconCategory.PlateArmor, Constants.IconCategory.DeathKnight } },
    { include = { Word "armor", Substring "demonhunter" }, tags = { Constants.IconCategory.LeatherArmor, Constants.IconCategory.DemonHunter } },
    { include = { Word "armor", Substring "druid" }, tags = { Constants.IconCategory.LeatherArmor, Constants.IconCategory.Druid } },
    { include = { Word "armor", Substring "evoker" }, tags = { Constants.IconCategory.MailArmor, Constants.IconCategory.Evoker } },
    { include = { Word "armor", Substring "hunter" }, tags = { Constants.IconCategory.MailArmor, Constants.IconCategory.Hunter } },
    { include = { Word "armor", Substring "mage" }, tags = { Constants.IconCategory.ClothArmor, Constants.IconCategory.Mage } },
    { include = { Word "armor", Substring "monk" }, tags = { Constants.IconCategory.LeatherArmor, Constants.IconCategory.Monk } },
    { include = { Word "armor", Substring "paladin" }, tags = { Constants.IconCategory.PlateArmor, Constants.IconCategory.Paladin } },
    { include = { Word "armor", Substring "priest" }, tags = { Constants.IconCategory.ClothArmor, Constants.IconCategory.Priest } },
    { include = { Word "armor", Substring "rogue" }, tags = { Constants.IconCategory.LeatherArmor, Constants.IconCategory.Rogue } },
    { include = { Word "armor", Substring "shaman" }, tags = { Constants.IconCategory.MailArmor, Constants.IconCategory.Shaman } },
    { include = { Word "armor", Substring "warlock" }, tags = { Constants.IconCategory.ClothArmor, Constants.IconCategory.Warlock } },
    { include = { Word "armor", Substring "warrior" }, tags = { Constants.IconCategory.PlateArmor, Constants.IconCategory.Warrior } },
    { include = { Word "weapon", Substring "deathknight" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.DeathKnight } },
    { include = { Word "weapon", Substring "demonhunter" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.DemonHunter } },
    { include = { Word "weapon", Substring "druid" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Druid } },
    { include = { Word "weapon", Substring "evoker" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Evoker } },
    { include = { Word "weapon", Substring "hunter" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Hunter } },
    { include = { Word "weapon", Substring "mage" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Mage } },
    { include = { Word "weapon", Substring "monk" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Monk } },
    { include = { Word "weapon", Substring "paladin" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Paladin } },
    { include = { Word "weapon", Substring "priest" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Priest } },
    { include = { Word "weapon", Substring "rogue" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Rogue } },
    { include = { Word "weapon", Substring "shaman" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Shaman } },
    { include = { Word "weapon", Substring "warlock" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Warlock } },
    { include = { Word "weapon", Substring "warrior" }, tags = { Constants.IconCategory.Weapon, Constants.IconCategory.Warrior } },

    -- Class Spells
    { include = { Prefix "artifactability", Substring "deathknight" }, tags = { Constants.IconCategory.DeathKnight } },
    { include = { Prefix "artifactability", Substring "demonhunter" }, tags = { Constants.IconCategory.DemonHunter } },
    { include = { Prefix "artifactability", Substring "druid" }, tags = { Constants.IconCategory.Druid } },
    { include = { Prefix "artifactability", Substring "evoker" }, tags = { Constants.IconCategory.Evoker } },
    { include = { Prefix "artifactability", Substring "hunter" }, tags = { Constants.IconCategory.Hunter } },
    { include = { Prefix "artifactability", Substring "mage" }, tags = { Constants.IconCategory.Mage } },
    { include = { Prefix "artifactability", Substring "monk" }, tags = { Constants.IconCategory.Monk } },
    { include = { Prefix "artifactability", Substring "paladin" }, tags = { Constants.IconCategory.Paladin } },
    { include = { Prefix "artifactability", Substring "priest" }, tags = { Constants.IconCategory.Priest } },
    { include = { Prefix "artifactability", Substring "rogue" }, tags = { Constants.IconCategory.Rogue } },
    { include = { Prefix "artifactability", Substring "shaman" }, tags = { Constants.IconCategory.Shaman } },
    { include = { Prefix "artifactability", Substring "warlock" }, tags = { Constants.IconCategory.Warlock } },
    { include = { Prefix "artifactability", Substring "warrior" }, tags = { Constants.IconCategory.Warrior } },

    -- Factions
    { include = { Word "alliance" }, tags = { Constants.IconCategory.Alliance } },
    { include = { Word "allianceicon" }, tags = { Constants.IconCategory.Alliance } },
    { include = { Word "ardenweald" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "bastion" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "faction" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "horde" }, tags = { Constants.IconCategory.Horde } },
    { include = { Word "hordeicon" }, tags = { Constants.IconCategory.Horde } },
    { include = { Word "kyrian" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "majorfactions?" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "majorfactions?" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "maldraxxus" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "necrolord" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "nightfae" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "notoriety" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "progenitor" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "rankedpvp" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "revendreth" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "venthyr" }, tags = { Constants.IconCategory.Faction } },
    { include = { Word "venthyranimaboss" }, tags = { Constants.IconCategory.Ability, Constants.IconCategory.Faction } },
    { include = { Word "warmode" }, tags = { Constants.IconCategory.Faction } },

    -- Spell Schools
    { include = { Word "arcane" }, tags = { Constants.IconCategory.Arcane } },
    { include = { Word "fire" }, tags = { Constants.IconCategory.Fire } },
    { include = { Word "frost" }, tags = { Constants.IconCategory.Frost } },
    { include = { Word "holy" }, tags = { Constants.IconCategory.Holy } },
    { include = { Word "nature" }, tags = { Constants.IconCategory.Nature } },
    { include = { Word "physical" }, tags = { Constants.IconCategory.Physical } },
    { include = { Word "shadow" }, tags = { Constants.IconCategory.Shadow } },

    -- Spell Themes
    { include = { Prefix "spell", Substring "arcane" }, tags = { Constants.IconCategory.Mage } },
    { include = { Prefix "spell", Substring "deathknight" }, tags = { Constants.IconCategory.DeathKnight } },
    { include = { Prefix "spell", Substring "fire" }, exclude = { WordStart "fel", WordEnd "fel" }, tags = { Constants.IconCategory.Mage } },
    { include = { Prefix "spell", Substring "fire" }, tags = { Constants.IconCategory.Warlock } },
    { include = { Prefix "spell", Substring "frost" }, tags = { Constants.IconCategory.Mage } },
    { include = { Prefix "spell", Substring "frostfire" }, tags = { Constants.IconCategory.Mage } },
    { include = { Prefix "spell", Substring "holy" }, tags = { Constants.IconCategory.Priest, Constants.IconCategory.Paladin } },
    { include = { Prefix "spell", Substring "magic" }, tags = { Constants.IconCategory.Mage, Constants.IconCategory.Paladin } },
    { include = { Prefix "spell", Substring "nature" }, tags = { Constants.IconCategory.Druid, Constants.IconCategory.Shaman } },
    { include = { Prefix "spell", Substring "shadow" }, tags = { Constants.IconCategory.Priest, Constants.IconCategory.Warlock, Constants.IconCategory.DeathKnight } },
    { include = { Substring "totem" }, tags = { Constants.IconCategory.Shaman } },
    { include = { Word "brewpoison" }, tags = { Constants.IconCategory.Rogue } },
    { include = { Word "poison" }, tags = { Constants.IconCategory.Rogue } },
    { include = { Word "portal" }, tags = { Constants.IconCategory.Mage, Constants.IconCategory.Arcane } },
    { include = { Word "stealth" }, tags = { Constants.IconCategory.Rogue } },
    { include = { Word "teleport" }, tags = { Constants.IconCategory.Mage, Constants.IconCategory.Arcane } },
    { include = { Word "void" }, tags = { Constants.IconCategory.Void } },
    { include = { WordEnd "fel" }, tags = { Constants.IconCategory.Fel } },
    { include = { WordEnd "void]" }, tags = { Constants.IconCategory.Void } },
    { include = { WordStart "fel" }, tags = { Constants.IconCategory.Fel } },
    { include = { WordStart "fel" }, tags = { Constants.IconCategory.Fel } },
    { include = { WordStart "void" }, tags = { Constants.IconCategory.Void } },

    -- Professions
    { include = { Word "alchemy" }, tags = { Constants.IconCategory.Alchemy } },
    { include = { Word "archaeology" }, tags = { Constants.IconCategory.Archaeology } },
    { include = { Word "blacksmithing" }, tags = { Constants.IconCategory.Blacksmithing } },
    { include = { Word "cooking" }, tags = { Constants.IconCategory.Cooking } },
    { include = { Word "crafting" }, tags = { Constants.IconCategory.Professions } },
    { include = { Word "enchant" }, tags = { Constants.IconCategory.Enchanting } },
    { include = { Word "enchanting" }, tags = { Constants.IconCategory.Enchanting } },
    { include = { Word "engineering" }, tags = { Constants.IconCategory.Engineering } },
    { include = { Word "firstaid" }, tags = { Constants.IconCategory.FirstAid } },
    { include = { Word "fishing" }, tags = { Constants.IconCategory.Fishing } },
    { include = { Word "herbalism" }, tags = { Constants.IconCategory.Herbalism } },
    { include = { Word "inscription" }, tags = { Constants.IconCategory.Inscription } },
    { include = { Word "jewelcrafting" }, tags = { Constants.IconCategory.Jewelcrafting } },
    { include = { Word "leatherworking" }, tags = { Constants.IconCategory.Leatherworking } },
    { include = { Word "mining" }, tags = { Constants.IconCategory.Mining } },
    { include = { Word "professions?" }, tags = { Constants.IconCategory.Professions } },
    { include = { Word "skinning" }, tags = { Constants.IconCategory.Skinning } },
    { include = { Word "tailoring" }, tags = { Constants.IconCategory.Tailoring } },
    { include = { Word "trade" }, tags = { Constants.IconCategory.Professions } },

    -- Profession resources
    { include = { Prefix "inv", Word "bandage" }, tags = { Constants.IconCategory.FirstAid } },
    { include = { Prefix "inv", Word "claw" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "crystal" }, tags = { Constants.IconCategory.Enchanting, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "dust" }, tags = { Constants.IconCategory.Enchanting, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "egg" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "elixir" }, tags = { Constants.IconCategory.Alchemy, Constants.IconCategory.Potion } },
    { include = { Prefix "inv", Word "essence" }, tags = { Constants.IconCategory.Enchanting, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "feather" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "fish" }, exclude = { Word "armor" }, tags = { Constants.IconCategory.Fishing, Constants.IconCategory.Food } },
    { include = { Prefix "inv", Word "gem" }, tags = { Constants.IconCategory.Jewelcrafting } },
    { include = { Prefix "inv", Word "glyph" }, tags = { Constants.IconCategory.Inscription } },
    { include = { Prefix "inv", Word "heart" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "herb" }, tags = { Constants.IconCategory.Herbalism, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "horn" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "ingot" }, tags = { Constants.IconCategory.Mining, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "ink" }, tags = { Constants.IconCategory.Inscription } },
    { include = { Prefix "inv", Word "mote" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "ore" }, tags = { Constants.IconCategory.Mining, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "potion" }, tags = { Constants.IconCategory.Alchemy, Constants.IconCategory.Potion } },
    { include = { Prefix "inv", Word "rod" }, exclude = { Word "enchant", Word "enchanting" }, tags = { Constants.IconCategory.Fishing } },
    { include = { Prefix "inv", Word "rod" }, exclude = { Word "fishing" }, tags = { Constants.IconCategory.Enchanting } },
    { include = { Prefix "inv", Word "scale" }, tags = { Constants.IconCategory.Leatherworking, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "scroll" }, tags = { Constants.IconCategory.Enchanting, Constants.IconCategory.Inscription } },
    { include = { Prefix "inv", Word "shard" }, tags = { Constants.IconCategory.Enchanting, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "stone" }, tags = { Constants.IconCategory.Mining, Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "tail" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "tooth" }, tags = { Constants.IconCategory.TradeGoods } },
    { include = { Prefix "inv", Word "vellum" }, tags = { Constants.IconCategory.Inscription } },
    { include = { Substring "resourcelumber" }, tags = { Constants.IconCategory.TradeGoods } },
};

return Constants;
