-- THIS FILE IS AUTOMATICALLY GENERATED.
--
-- Changes to this file will be discarded, ignored, and every other negative
-- word you can come up with that has the same overall meaning.
--
-- This file is licensed under the terms expressed in the LICENSE file.
--
-- Client Version: [[@ build.version @]]
-- Build Config: [[@ build.bkey @]]

if not ([[@ loadexpr @]]) then
    return;
end

local LibRPMedia = LibStub and LibStub:GetLibrary("LibRPMedia-1.0", true);
if not LibRPMedia then
    return;
end

local icons = LibRPMedia:NewDatabase("icons");
icons.size = [[@ db.icons.size @]];
icons.data = LibRPMedia:CreateLazyTable(function()
    return {
        file = [[@ db.icons.file @]],
        name = LibRPMedia:LoadFrontCodedStringList([[@ db.icons.name @]]),
    };
end);

local music = LibRPMedia:NewDatabase("music");
music.size = [[@ db.music.size @]];
music.data = LibRPMedia:CreateLazyTable(function()
    return {
        file = [[@ db.music.file @]],
        name = LibRPMedia:LoadFrontCodedStringList([[@ db.music.name @]]),
        time = [[@ db.music.time @]],
    };
end);

music.index = {
    name = LibRPMedia:CreateLazyTable(function()
        return {
            row = [[@ db.music.namerows @]],
            key = LibRPMedia:LoadFrontCodedStringList([[@ db.music.namekeys @]]),
        };
    end),
};
