-- THIS FILE IS AUTOMATICALLY GENERATED.
--
-- The database is stored in a highly compressed form to minimize space usage
-- when the contents aren't actively required by any addon. The full decoding
-- chain can be found near the bottom of the associated library script files.
--
-- Client Version: [[@ build.version @]]
-- Build Config: [[@ build.bkey @]]

local LRPM12 = LibStub:GetLibrary("LibRPMedia-1.2", true);

if not LRPM12 or LRPM12.db ~= nil or WOW_PROJECT_ID ~= [[@ project @]] then
    return;
end

--
-- Database Unpacking Routines
--

local LibDeflate = LibStub:GetLibrary("LibDeflate");
local LibSerialize = LibStub:GetLibrary("LibSerialize");

local Z85DecodeTable = {
    0x00, 0x44, 0x00, 0x54, 0x53, 0x52, 0x48, 0x00, 0x4b, 0x4c, 0x46, 0x41,
    0x00, 0x3f, 0x3e, 0x45, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x40, 0x00, 0x49, 0x42, 0x4a, 0x47, 0x51, 0x24, 0x25, 0x26,
    0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32,
    0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x4d,
    0x00, 0x4e, 0x43, 0x00, 0x00, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c,
    0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x4f, 0x00, 0x50, 0x00, 0x00,
};

local function CopyRemainingKeys(src, dest)
    for key, value in next, src, #dest do
        if type(key) ~= "number" then
            dest[key] = value;
        end
    end
end

local function DecodeZ85(z)
    local floor = math.floor;
    local strbyte = string.byte;
    local strchar = string.char;

    local c = 0;
    local b = {};
    local p = strbyte(z, #z) - 0x30;

    for i = 1, #z - 1, 5 do
        local b1, b2, b3, b4, b5 = strbyte(z, i, i + 4);
        b1 = Z85DecodeTable[b1 - 31];
        b2 = Z85DecodeTable[b2 - 31];
        b3 = Z85DecodeTable[b3 - 31];
        b4 = Z85DecodeTable[b4 - 31];
        b5 = Z85DecodeTable[b5 - 31];

        local v = (((((((b1 * 85) + b2) * 85) + b3) * 85) + b4) * 85) + b5;

        local div = 16777216;
        repeat
            c = c + 1;
            b[c] = strchar(floor(v / div) % 256);
            div = floor(div / 256);
        until div == 0
    end

    return table.concat(b, "", 1, c - (p % 4));
end

local function DecodeStringDeltas(deltas)
    local strings = {};
    local offset = 1;
    local length = #deltas;

    while offset < length do
        local sublen = string.byte(deltas, offset);
        local common = string.byte(deltas, offset + 1);
        local prefix = common > 0 and string.sub(strings[#strings], 1, common) or "";
        local joined = prefix .. string.sub(deltas, offset + 2, offset + 2 + sublen - 1);

        table.insert(strings, joined);

        offset = offset + sublen + 2;
    end

    return strings;
end

local function DecodeNumericDeltas(deltas)
    local numbers = {};

    for index, value in ipairs(deltas) do
        numbers[index] = (numbers[index - 1] or 0) + value;
    end

    CopyRemainingKeys(deltas, numbers);
    return numbers;
end

local function DecodeFixedPoint(fixed)
    local decimals = {};
    local fractbits = assert(fixed.fractbits, "missing fractional bit count");

    for i = 1, #fixed do
        decimals[i] = fixed[i] * (2^-fractbits);
    end

    CopyRemainingKeys(fixed, decimals);
    decimals.fractbits = nil;

    return decimals;
end

local function DecodeCompressedData(source)
    local output = source;

    output = string.gsub(output, "[^\33-\126]", "");
    output = DecodeZ85(output);
    output = assert(LibDeflate:DecompressDeflate(output));
    output = select(2, assert(LibSerialize:Deserialize(output)));

    return output;
end

local function DecodeNumericData(source, options)
    local output = DecodeCompressedData(source);
    output = DecodeNumericDeltas(output);

    if options and options.fixed then
        output = DecodeFixedPoint(output);
    end

    return output;
end

local function DecodeStringTable(source)
    local output = DecodeCompressedData(source);
    output = DecodeStringDeltas(output);

    return output;
end

local function DecodeStringReferences(source, strings)
    local output = DecodeNumericData(source);

    for i, index in ipairs(output) do
        output[i] = assert(strings[index], "invalid string reference");
    end

    return output;
end

local function CreateTableGenerator(generatorFunc, ...)
    local data = {};
    local meta = {};
    local args = { n = select("#", ...), ... };

    local function LoadAndReadSourceData(_, key)
        local ok, result = xpcall(generatorFunc, CallErrorHandler, unpack(args, 1, args.n));

        if ok then
            Mixin(data, result);
        end

        setmetatable(data, nil);
        return data[key];
    end

    meta.__index = LoadAndReadSourceData;
    return setmetatable(data, meta);
end

--
-- Database Setup
--

local db_icons_id;
local db_icons_name;
local db_icons_strings;
local db_music_file;
local db_music_name;
local db_music_nkey;
local db_music_strings;
local db_music_time;

-- The string tables are kept as a local so it can be garbage collected when
-- no longer referenced by other the table generator closures.

local icons_strings = CreateTableGenerator(function() return DecodeStringTable(db_icons_strings); end);
local music_strings = CreateTableGenerator(function() return DecodeStringTable(db_music_strings); end);

LRPM12.db = {
    icons = {
        size = [[@ db.icons.size @]],
        id   = CreateTableGenerator(function() return DecodeNumericData(db_icons_id); end),
        name = CreateTableGenerator(function() return DecodeStringReferences(db_icons_name, icons_strings); end),
    },
    music = {
        size = [[@ db.music.size @]],
        file = CreateTableGenerator(function() return DecodeNumericData(db_music_file); end),
        name = CreateTableGenerator(function() return DecodeStringReferences(db_music_name, music_strings); end),
        nkey = CreateTableGenerator(function() return DecodeNumericData(db_music_nkey); end),
        time = CreateTableGenerator(function() return DecodeNumericData(db_music_time); end),
    },
};

--
-- Database Contents
--

db_icons_id = [[@ db.icons.id @]];
db_icons_name = [[@ db.icons.name @]];
db_icons_strings = [[@ db.icons.strings @]];
db_music_file = [[@ db.music.file @]];
db_music_name = [[@ db.music.name @]];
db_music_nkey = [[@ db.music.nkey @]];
db_music_strings = [[@ db.music.strings @]];
db_music_time = [[@ db.music.time @]];
