-- THIS FILE IS AUTOMATICALLY GENERATED.
--
-- Changes to this file will be discarded, ignored, and every other negative
-- word you can come up with that has the same overall meaning.
--
-- This file is licensed under the terms expressed in the LICENSE file.
--
-- Client Version: [[@ build.version @]]
-- Build Config: [[@ build.bkey @]]

if LE_EXPANSION_LEVEL_CURRENT ~= [[@ expansion @]] then
    return;
end

local LibRPMedia = LibStub and LibStub:GetLibrary("LibRPMedia-1.0", true);

if not LibRPMedia or LibRPMedia.schema then
    return;
end

LibRPMedia.schema = {
    icons = {
        size = [[@ db.icons.size @]],
        data = {
            file = [[@ db.icons.file @]],
            name = [[@ db.icons.name @]],
        },
    },

    music = {
        size = [[@ db.music.size @]],
        data = {
            file = [[@ db.music.file @]],
            name = [[@ db.music.name @]],
            time = [[@ db.music.time @]],
        },
        index = {
            name = {
                row = [[@ db.music.namerows @]],
                key = [[@ db.music.namekeys @]],
            },
        },
    },
};
