language: minimal

addons:
  apt:
    packages:
      - luarocks

install: luarocks install --local luacheck

jobs:
  include:
    - stage: Build
      script:
        - make check LUACHECK=/home/travis/.luarocks/bin/luacheck
        - make test
      deploy:
        provider: script
        script: make release
        on:
          branch: master
          tags: true

notifications:
  email:
    on_success: never
    on_failure: always
