-- THIS FILE IS AUTOMATICALLY GENERATED.
--
-- The database is stored in a highly compressed form to minimize space usage
-- when the contents aren't actively required by any addon. The full decoding
-- chain can be found near the bottom of the associated library script files.
--
-- Client Version: 1.13.6.37497
-- Build Config: 3f54383a77a7c4774335d74b7e8e8f56

local LRPM12 = LibStub:GetLibrary("LibRPMedia-1.2", true);

if not LRPM12 or LRPM12.db ~= nil or WOW_PROJECT_ID ~= WOW_PROJECT_CLASSIC then
    return;
end

--
-- Database Unpacking Routines
--

local LibDeflate = LibStub:GetLibrary("LibDeflate");
local LibSerialize = LibStub:GetLibrary("LibSerialize");

local Z85DecodeTable = {
    0x00, 0x44, 0x00, 0x54, 0x53, 0x52, 0x48, 0x00, 0x4b, 0x4c, 0x46, 0x41,
    0x00, 0x3f, 0x3e, 0x45, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x40, 0x00, 0x49, 0x42, 0x4a, 0x47, 0x51, 0x24, 0x25, 0x26,
    0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32,
    0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x4d,
    0x00, 0x4e, 0x43, 0x00, 0x00, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c,
    0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x4f, 0x00, 0x50, 0x00, 0x00,
};

local function CopyRemainingKeys(src, dest)
    for key, value in next, src, #dest do
        if type(key) ~= "number" then
            dest[key] = value;
        end
    end
end

local function DecodeZ85(z)
    local floor = math.floor;
    local strbyte = string.byte;
    local strchar = string.char;

    local c = 0;
    local b = {};
    local p = strbyte(z, #z) - 0x30;

    for i = 1, #z - 1, 5 do
        local b1, b2, b3, b4, b5 = strbyte(z, i, i + 4);
        b1 = Z85DecodeTable[b1 - 31];
        b2 = Z85DecodeTable[b2 - 31];
        b3 = Z85DecodeTable[b3 - 31];
        b4 = Z85DecodeTable[b4 - 31];
        b5 = Z85DecodeTable[b5 - 31];

        local v = (((((((b1 * 85) + b2) * 85) + b3) * 85) + b4) * 85) + b5;

        local div = 16777216;
        repeat
            c = c + 1;
            b[c] = strchar(floor(v / div) % 256);
            div = floor(div / 256);
        until div == 0
    end

    return table.concat(b, "", 1, c - (p % 4));
end

local function DecodeStringDeltas(deltas)
    local strings = {};
    local offset = 1;
    local length = #deltas;

    while offset < length do
        local sublen = string.byte(deltas, offset);
        local common = string.byte(deltas, offset + 1);
        local prefix = common > 0 and string.sub(strings[#strings], 1, common) or "";
        local joined = prefix .. string.sub(deltas, offset + 2, offset + 2 + sublen - 1);

        table.insert(strings, joined);

        offset = offset + sublen + 2;
    end

    return strings;
end

local function DecodeNumericDeltas(deltas)
    local numbers = {};

    for index, value in ipairs(deltas) do
        numbers[index] = (numbers[index - 1] or 0) + value;
    end

    CopyRemainingKeys(deltas, numbers);
    return numbers;
end

local function DecodeFixedPoint(fixed)
    local decimals = {};
    local fractbits = assert(fixed.fractbits, "missing fractional bit count");

    for i = 1, #fixed do
        decimals[i] = fixed[i] * (2^-fractbits);
    end

    CopyRemainingKeys(fixed, decimals);
    decimals.fractbits = nil;

    return decimals;
end

local function DecodeCompressedData(source)
    local output = source;

    output = string.gsub(output, "[^\33-\126]", "");
    output = DecodeZ85(output);
    output = assert(LibDeflate:DecompressDeflate(output));
    output = select(2, assert(LibSerialize:Deserialize(output)));

    return output;
end

local function DecodeNumericData(source, options)
    local output = DecodeCompressedData(source);
    output = DecodeNumericDeltas(output);

    if options and options.fixed then
        output = DecodeFixedPoint(output);
    end

    return output;
end

local function DecodeStringTable(source)
    local output = DecodeCompressedData(source);
    output = DecodeStringDeltas(output);

    return output;
end

local function DecodeStringReferences(source, strings)
    local output = DecodeNumericData(source);

    for i, index in ipairs(output) do
        output[i] = assert(strings[index], "invalid string reference");
    end

    return output;
end

local function CreateTableGenerator(generatorFunc, ...)
    local data = {};
    local meta = {};
    local args = { n = select("#", ...), ... };

    local function LoadAndReadSourceData(_, key)
        local ok, result = xpcall(generatorFunc, CallErrorHandler, unpack(args, 1, args.n));

        if ok then
            Mixin(data, result);
        end

        setmetatable(data, nil);
        return data[key];
    end

    meta.__index = LoadAndReadSourceData;
    return setmetatable(data, meta);
end

--
-- Database Setup
--

local db_icons_id;
local db_icons_name;
local db_icons_strings;
local db_music_file;
local db_music_name;
local db_music_nkey;
local db_music_strings;
local db_music_time;

-- The string table is kept as a local so it can be garbage collected when
-- no longer referenced by other the table generator closures.

local icons_strings = CreateTableGenerator(function() return DecodeStringTable(db_icons_strings); end);
local music_strings = CreateTableGenerator(function() return DecodeStringTable(db_music_strings); end);

LRPM12.db = {
    icons = {
        size = 2733,
        id   = CreateTableGenerator(function() return DecodeNumericData(db_icons_id); end),
        name = CreateTableGenerator(function() return DecodeStringReferences(db_icons_name, icons_strings); end),
    },
    music = {
        size = 192,
        file = CreateTableGenerator(function() return DecodeNumericData(db_music_file); end),
        name = CreateTableGenerator(function() return DecodeStringReferences(db_music_name, music_strings); end),
        nkey = CreateTableGenerator(function() return DecodeNumericData(db_music_nkey); end),
        time = CreateTableGenerator(function() return DecodeNumericData(db_music_time); end),
    },
};

--
-- Database Contents
--

db_icons_id = [[
-A1Y??7PxQ)@WtvMk9KCIx:O]2j$.?-%J$({ZF=<9O%R(qDk+iByKOp3O@ze0$b=(FW3-<!vAtBT*c[CAs%TA)&?v}]Mmyf[6ldu)@4J3<55Le6$KOo9%j
/5(X6f0xPd:QDa9Ho]z7CeuD[><+5{nY>+ex9MH-HpGeFTL0Cgze<K#IQ=)GOLkL@#Rkp0+>WJE^mQLi8&/@&&iU#O+M/70h7&LJ/.-].@O>YnzyEK>YbE
b]a=:EC.Y&CqIks^<qik%xDqI%yB@^$I::MV.juW82m#9OamA(@MHRyEX>X6.LKq25+.-]bo#Ie<LwuM4Ny]R)RX)L}E9cP^T#SbXqq2gOhaHiyGolR%9e
}BM{A}COhi&h5.B-Sdhe7vnF(/l{]Z$95d]j5/Awfd8}AVhOcW=yAS4]Nw(FP@*#PNt2lT}d{z&bpgNYn=4?-9WoMIRXrR+):Kl$8eip>^uk2g]u*3qA-5
CxUobRQxJjN73Eak%aII}2!l:L.b.VsOb.fGuvi?!]hIH+^EaV0)$2!zh5n75Z<*9oMEALfbW7mP[bk[G&Cr+}nks#=W/ZzLHxn+KhByRt?fEYg?D=uVij
pK/q9A^Cf[ckTd/9yXNAhS7Od<8nXz@ZxK/zTJ0W)oP.!Ehx#V]e&(H}V3P@3
]];
db_icons_name = [[
v{D<TMu!n^mDND33wFT<b%=R!JdK[X^-NesfD!eVgZJpFCOR$?V=+5zfTeC.lGQ8&0qQys?-f?$l{JKkj2n*Ucu=5t8B!cQ2iD)fo=?qk4b#^q1
]];
db_icons_strings = [=[
?f^[s<f)ykqq}}2*n?md{bMhg5FGdd*et5t]csW2GE1ds86?>SEX?ti}4xu1S{Yd)*VOIm-ED&YKQlL6b9%}@3a4$T{Y2}i-P]83*qtx)!)kR6Oopt:heQ
1m?7E21uB-?p6lh<{S=)C}5X1qBTe7@snlqBjw7I9iY>2.N)e03e^Ys42bK28Y1]CJma8Y.^tx:4FsYpO)hd$J+kf}}lIsWQf/]@Ugrbs%<8Vmeh<J%e$M
AGjiX!]oxL}m(k9xc5woYzuVTY:C/M#9Yc&YJpBzb$K=6?Y^K{cGWaIPeHsIB$)l{n6dF5VeWi^iu4^qoBblF]z@BM1i[DTG$@fvs+X7Awu*2bB4.ZfOW]
Ns<$]:7o1@ZmeK53jzXQbeomhu<92BR=QswUJWQwLMv=ZNqeL3TSp)^/y+&mEqXt}0V!XR!Zlbe/ATpCI7E=!ZGMSM?uEna3W3104/8%(DH3d*dWu8Y!p)
Ef$M93dGi4Ex?DOMN0WmBG]M7/+2-kdC:/N$2R+}Dj-eV-U+ruLF]hzh=GDNv^O-1b78wy2Z-<3U9hS(mna&hqK6-/pyxmLd^%S]Foi:&UshTF6re(:N%e
mjXWxUYIM<>UTVUw(R:<s[uf1WW27vdDUe+5m)$>Fc1j?-X<5@pNX8xB^wE{@1mwDW3St103ou#c!?[ULJKLCn+joQE76Y[79#dx<R{ePQST^PN6NQJUb4
]v1cn(-j0Jkz&xD26tb(@$d@4QuXH3}/=j-nop7+WE1@(y+Vynxb3S2^:Yf7l!fNg1JVbHA7-u5x[cV@WCGa:)-![*63vg2.1N?<?)[B}$7RoMD#&&bK26
7>Buo{Zrh2Z2s.-V(xv+:iqYHgN*HWu#Z3rNr3JTH4E?JBvKfpDV^Q&FM#QOST#=5qo{31OB-qBe3mlp8#$lAOqAK*sfaw<7>lQl6Rk+AAzxFNPjXIhB=h
9@j[CmLa^s49jJg{np47{>v4W%dqsOOb@bhccoS11]dA!sEe#Udbj2{RazS9*RyQ{>LB+#}j8}RPaXY+YGvVzmg!Y37Q:decqYVqron5mdSl[7Bn&LFW-I
^RuA7=xu.C=+^&Y@#FHQ9%LcFU&EgPQ].NgSA7yZ)sKrU7Y8d=VyCCrJPsl*L?qs0ZT?d5(rd)llnIAsk)63+5r4zI#K4=H%UjKpjydh>7flecl4}Ub1sx
gt}@/A&2c}J3qd}:f26%k5MNP)p76hQ-NeZ+2yAcY{iNAOVA}OAFA{z=VbvgYnr(mM@$.bJuEL2?Nh=9(8*r&oDW*bc(nm(i7#:x)MI1g+!Ub2qA@eEMoS
JXsqHrUd[.41Td<4gDdseS!/xg7<uG<w{e3SVFV&gJTGAXYEaVwF?IyxQC4wtd:@o>mRELUoIMF4lOxcuE.aUOC{azK?(e+ciF/-ktHn4$ozEwldOkIi3T
CO$N^oII*4chdF>MNP/VDvkS9q-@>x*.ID!DlVxg(7y&Gkr/jPh(!g9[BtqxF}R#c7rb6&0uAeso0sL<dXbz]PONccgAMpC)]S1L.?jRIm?9b}.v-:GH*R
tcn(H@x(Kzk!zGzQy7pn00[[m^R(UpBsf]8vY1hg414WAeT=@%Ip7FezYm%Ky1&O(6.a48L?9qAvz}}j>{e3[H%cKA.xsiv=T)c[iV)$aZPp$<@VX4BoKg
R2(KqWgDei^{AYY#XU%lWY>FCjKOGLt)o4+B#uCGFRV>h4(/J>a]dEphH6H4B4D>dTh?YG)QHjm0ngB5$TZ!rzOQb[TA)9H0OL7YsKeMLM=%yKg<NJ[5:I
2ylT>Mml<[cCA(n:[Mt9W#xi0E:v=><bU0e>eDj3fwX6fZB3N8{iUuaA^4Oiu6O=I.m9Bo8LdUqV]zB[I9n47s)2?[eG=JqMp5!CEH[H*Hy3=f^4[tU]oN
RjvCSQc)WejAYA^NZiVHFTM8ACJQz(b5wURsBX[v=yhHr1MvP/F3AcKx9)#K[vKZkXT/d%bCB?3rc)*&&C[=sHr}cja^xpWd3F=aLB&j$9}bR:5*91#I4W
T(VqvG4>I[0FQJ@0hvGuu?<5%6q{uR7jb2WVOIM!a>tiA%B0}dj#77!U:G}gSU6ftw93o}@D(o<Et[=X9]B:Ea7WjB8>VSX03#+ezo9so(wUBJ.O@{<BH2
Dfug+PVH$7AGtJvohOrFotq<c7.*sp?v8H3y2N.V4o$2rX7AI1jz[f-cunt*{T7x9@(dqI?w?:YQTAD5t9TH^D&LamBS}P/8=5jc5td{Jn5bMW7z>ssl+O
C36wv0jkYjFrghOiRd2r3}wNeV*3gq[wkM7n?Zb{SU%bKH}=5eu(740$GT.wCf+Fej*.qRN[+7?l]fJEUjToHX@zt&^?[t+p*a^gP7tuW+*8}2<Cnoz2nn
?emKL6ZBj4kDp7bQ.HgS>l1Fb{Z0p<3cl.C<[VBlxQ-T6aQzXIKhz0upP%A+{]1[0YgfH8m$p:iw:K+}.06r%bxyqk-@/uSIK&=h8.VS2@mEQ/0kj<P/Nh
@WkOW$kFU}:EO2jfI9*5%!?<j-9yX*iW)A@UF]3:vHZkcNev8n0fh.qEI.5S{Ks[6jU-%S$A5QWp.oBSAnd^{9Xh7SwEWmtPEoBDTiwIubumd(J>0z$&3m
.n%xeM)hkQfwz?Vfm=F4>J4t2>sRL9Reir]0fT$x7&71?Jvv-uN$rzFJ0:WMC/sq9k@?3uSN$KU*qPeK*Op=4G?Gu(C%Y^IVz^x0%kcL<vM-xnwrxwRg^r
$1bj-5/8S-q@VaTU&vR+<m&{4jahDFq&ZT&rw]nmbd98)F(geWsYs4jYRLv2hF9+vZ:&<C2h$8@G?Zvr{pRIrE@+9IpoYK3G]Sq<S8Byl4@Y.g+a4{K^m[
uUO8#m!-}@-1-X4)8WJtI-heqn//<}KPo0RKPeij3h<A2W5KuA*5*J!bF<KkDfLS#0mvd&TZ}G#2NTV5-v8A/7PMN/=IVKvNsVq0zj.?LGMdQ(32x]Oc7U
*4pq0)<F97.GIcFz])g*x1]$JUs[PP4G2?H]gLidaXl)-3#yyg>c]eQ:l9bj@>NVS7C>BI@2Lv/zl!Il.KLrn(GN<9(0?a0BOs}y&:8vIcGA#V*?lU%V3>
pYuZS-eZg35ahOJXYDP3sX<hW5&colKgYM*6YE4L/ThKPQFp7#*J:cPkNzA<W7EMNCuiqZxK(U%P6J%>V3:V!N=KgjGo9OZ}ZC4%A-?}M9=FI!.#@>Zq:F
Gy&%?=CZ^<eHlXv!FFm:x^cjh6uI#?)k!rq9-bp<HtDu?]28EbMv8Gj$MWo>9%{luE4IILgtYrxn!%@gQmKn0JgFn6R>G.WKZVUPxZNlpcL#HD^j6tD=>5
bl2pwi:>$IZPdCh*9DwO%&Gw)NewbMM9sItrnAV9/-T2d<tm9.42!%pNkcTLDD^)@NvcLo^?$ScK)JISU6)Q.0VN$rszg)TB6RdfWKCCUY!l6PFUr-Von^
W?zGITR0:3FP/Q:J$p=sEj]lOk$eTGrC*aA=iXYhu{K0Z#b1mT}7DTpSD&o?m.>!{*G.=9ieS2-7qHQ#rXRx?^hkE0TlM/+J*%KCh}:&.L7{5upWT]vf-I
C+JhO4)^.>c@k8ZrwDM#GKC*zqK&Mus3uHtJamhht.NC*XE3ksUa9iE<U4jr(da=TFT=Pbc53qq1*y+Z{p&xwbEsp2Z(y@l2M:G{F}n:n{={1f}9z#!>5<
2HPN1k}T7L<Cq+C0vRETD4tVovm5//=nKd65xPh>STB[Z%d}:YGvQW4?QCMh{O)O5J#+t)Cn!+rnwZ0.tjBL!R0{E+g[i}^Y]dIhHlYE=qn<#Tl=XA<NE3
YulW}iEeSd}l4![$Nkr7O5]Z3zj{)E$(J.7Aev3*BV<=>1NzxRvNItCRN3?oY40Dg)@3{nGPBUkT+@!UQ>kCqkfpPV?[WR&VL<wTmD6l=/T.!pg}>EE9p?
P91cFZ^/k[MY*YUXPm3J1}r&X4EnpuEwS&r&tP!A{]4TP3Tz2hZ3hlIfFEXwVZG[WuL4=V2AF0k)R#JQaYx%GcQq1I&.Z!Gh:o@NoW7y@a+Gy73tN53k68
B6}A54CRnf/a)}dUReKy*t:]Z4L=c@6Qf-TY1LCtRb:32ic:%5Kaa0o82T!xSYISo-m*jJjb.U+c{?V(5zTx:=4B.<MtOPG^hYz1C5?/-w}=!9ajF9-y}n
.>8o!pEvgVp?L<Ko-9sj{%=<a(/H)M!!}.[9Jt<x*5S.<hfucy.FJB&<31@CcoHfTRlKmSQiiqS<aY#):Z*MCAUA:4kM4pe}MhoQAxF62S/$NQY1O0/e3{
JZ-uChsR2E8bu7.2Tcz&fxkCfdp{<jPqS8%4f?8ht@.ZWMA1#eH.L/ikOeCZ2fOFMeb()EEC*&^^6p./uXtWZ(d7!-2IZbMUT+#g9op(*}tbO1:AQ9A>q)
Ba7.&CIAilK:(M)gkUY?^4JR)db)p?M>r^C6Ry^a4A[oO^(rgAs?j/={]VsW[#EEjzMT2P(IXBa3rT4y%z>j)&qjw=EB8bhp[*mF0Pf1&N!dX&tpteM+Hu
<!zRk1&tps34]@h.ZIJ*#s0+mI[{2T97UDS1Tu[v.Xh$1KcB}2vIf48dFpH]S*0{LzX[a@!)cpfFj*q0cI+ANr(tu9hQ(F@G7&m!ER9fF.YJtxYeFUq9=B
m.163Ez:C+jrk<..A1E3I>Do7GQAxwoM=v$Jrx*2oI3BJLDM6wl@7/ag$XB.{Q-?3$(CEV]C/fEm67C]UbA(<AKdRV#H+m2<sLDOG]tIx6u+&){}AtGw)R
hT&kl!ue<Fnq=DYee.b}n2HV6R*p<*U8lI<gLp4.4iuJfqP:L=RFN#kE^FArnqjWU+*{Mv*q[ABcN!Kr?vi=OMdS29{>wKX&P-Wfy}2.da[/SZy.3JA=LU
v#=Y!:%YGQe@^cUv&15q[fJN@Od<ny9z-YIt3zrN^6e-OG4UPCskn6P>J}Lm-)5Ie[oFVo]]4v%SH{K0=:0MU8E{VMF@Z7URvlM}y1B(k&RHO:2<g-L$zh
G$BrWr9EFr$N&8F[I8.ljFs0dv+^tknQ<>!L#B:>p/yvWPlm.swVy(mnJu:Ub2%@+P0L&Q0I0rjZ>HlTcpXv1A&0rnNAYGj&cuCBT(c5?J}z3.Wa%D.n5D
Zo}o7<B&>X:u36{(yQDr8m>qO9&CA}#bwh82A4EZ?P}.[W7b@<q2rMk?S1(=cR}h*7SzNH<2NF-!cQmp3/Qe.8{?7g!TFtsjGM&F=mAR.0lQff]S>c=}=7
RGYf#SrjwbQkmj#5]Ro&[r})[b0ZAZ^]OlJMX>AdW6r<LJg1}Q5ljv#:%)Ca5zwN?@:#@y=rqxxfkU%nkNW-$3n:f{l9W:[VL9)A0!@t18F?U-rGG8m4sq
@Annh{#XygE)!+Y8$H]z<J42ogEC^Y/sEsRsG?^*oX<X(F.%Cg5+qX0Hb[0?SN21qy5$J+w]RYTqF+x-]iEVCo]b=PT!BJV(uV+cBNk^d+DP0x0d!@{6>m
9BmQ4vgZ(95UScoCdig%@)GvZR]c1)[!qvKIT<aRO)m!^5@kbX0naIS29:S/k9fv10YSEUS@yX)]ip$u4P36b&29YC@Rl/*4UwJLXVYQlp>:Qb1<LoE{]2
t]^wy>>]&gUIhPKL(#NWgWsfQorM2]Ud0oX2HB3fOh8FIABL26?%k3t=qzvjY[FIS]ALsqVbw{O(QL=FTp1*e>9h3qCq15C7tzhQ)kk$]sL?A2bAlhgr9o
Lv[(ODE6WL/oU9CH^zB%7B>9]A1Z0F1i(*L39iH#zu0(H<Oe<d/}/xU12v$X)smP:A*h4Uvi^Oh]I2FB[AzfTA[/H02(1N1D*Rm*$(U}M9de9f)6@b^gQ4
cqi2&b.b73/K*oWo(CU#0UXn0jS/tbYZN4jO1Qmd!%[T6y9orqpv/]e(3{*HP6uDXzjd]kp)]h>dNiuvGZb)#%8RL8h7@G!1bfB}<K0uwHB+?Dr(3Y-j/*
vlAiZOl9Lw-)Fp@G}!B^BnBMcm-+sQ6.+0SI]Ngb3Zvz@>ADRJ!)$LsjK#[xQfedid4dFP!d-gD}a$Ih!EEiw>4FFNx(NA!N%QcR@+BFS[PH$y/@-xAa<u
]hL[OQ+8+@=SYIDm&Pm2mOlJZZ^ldkM18>L*O{2jehGYerR!]3+9A@+[dxj$gia=Fc(bj9[/0fnWV9ce]g?:3Xw[R>L[1ss&&y:T+$X$W]@aB])pBvDi?4
JkEY!H5%DaUPuUQMhv#KDO2%w71ij]h8qBh8lG?L-5mK=lS=5Kb&5wlyQRTab.63vgv{*6yaPUhl-/?>}7qQ9W!THC&Utrk92N3PVV<ssV5}h(79XDhx$0
KC5=vTi4CTl[1nYNOYQz(:{^[z!OWC&jx}!L:05TwyK?gA/XYUQf9PiBa1#^uAqo#?[JIl]e+}N=J=+H6dCJxG<uPYW[)r>$ddUS$BtoWFROw/jGD:3J9P
8[vUsB>yR?L/Z{1:E/72[)FT%#8+)$QEU&/X1nRLo9DXGm1>z)8REYeZhPRB0zg9W@]wj8#7]svkXRadYzQ!Bq=YA2kJ$D>SE3rKX<p07o!&8v0v&/$A&U
:h#9hNPnqh-ndFqQ5e8a>LMp-RHa^e(MLA[d-{m}V@ztdn^8f?[xv=Fa]>W?<p?KLEyTisFVWagD+}B20E<08-BjfO22tp]Lf]bp84+b^QcF%!sy)t5Zh8
Hgmq4Hw)Gw2J26quJI8@CHDs8fIuRS(0Zs*1fEnH1Z+N1o2bZB]q=)0OeFNse5Y:N0*(.dnPEegUC<Qny@uZNy#&8%?!AwK?<y^Q&i&*fU.zt2I2ZPK2:E
QcfT}SOZcR@wNxruTY^/xnSIwI<)S8K:I%c+@htNsZvsR]r4C<T{C?kcR7:3Fk+RCXETbSWb6deD*bBe}vdNkgKoSuV&GUly3uzN-C&}Lp/4!M8.^U{3@}
#Ss!OfY*r[9yst$+&L5$]b]4la/8T7$?EY:Kpr(Dx8@}@rudpg5o%}?6pl@XbBMppjO#S&ntYAM}Mz=.sn@SNE6qK6Qo+V8r1HMq:&F3t^S8:%QfSe2>^*
/$().(1fD]jq60rpCDNL!vN*6{xcw@Y<FI$%o8iNW(D-kyoa1WRDfhazfI9gFg(k4s.TphI6%KyTdUE9aOm[.Pj7U]L!#9!%EF{%wV2r{p3?^edXPp1$}%
0hc8prPSgNQQ:e[?]CK>rBc^[A(6EDKcji!)]@o9TZbo>BsEw+[#ttM)Xel#TB}ORb56iPP#jU}RHMbk:^z5(/P<Lz11.W0QfqX?njt&:1wT6lIQc4G.h%
-#/BS2kD>P.Jt3&oXF#MLFf[zGAXU227S:-}Q[sn+i+v+>G08K)HPA-l0f9//pC#]>)G/a[<89/K<NQN$ELmNWohuZ[ok)d:roNDwTn9b+AIlkDdQ+}?OW
0OPTN7/2{+c4c%T7w?ah/X?#-mL0@oXI9*ip(-9yy)iUv&uFyoo+dsz-4ovKcZWgcPYa{b&K.y?C^7#kU*{6ZaIX}Z[RZa5eJFXe7z/E5&yd5iAdpJOeLE
]C$N]I:X*$B-(6(qB&/o@d<q8cxHYM:h1X{2v.s.[7TN)Tt)fC#M/PeIaYnLbV@b}YD}mvr7Vb:K86qx&.mzKuYhWz@}zn$e[.}@aimeKG=l+^aCOXeDz/
S{2dVdyUD@96x!A%+ip(q}9KwoN}5oZ$p@+../Y6!8w=XV2yUA1sqUgW]0?Xs&1d6U+=0>ZxXG-UzLMW5YUDf!3:*.62[w}Yp1Lyr[:5RajmT<Ia<2$eHl
Qitq5TKT#&hZ/SsX76#POv<KrLmF*VmDk!?6)zx]k$k0T5=b9a!GxjC<6A9[!GW[M&^<7EJ*&26FCU+]Ked&XIs&l5A%}OBK*cGxKe[n>X0s9Fh8{poTj5
.+cjgY>FWdwhT14:ZSi?9/PzJL1{ScBUIImnnTH2M5XC*ibaSK44Z(J/d()M1w4Rx<(O.v4=1MYeotRzG&L#/X673rq:01zV7qEtot/l3X5RXSV]nTuyoK
.)OkR)>T55r6Lw+Ie6f8KAM=Kc2nVh)p-!7fqQb^RfrXLD3=vGC#i4K@K)u5r=&MAFiR4vaBlkV@b$V=pr%^V+=**s$a5HUnx?-&<7O&-%-Mzg(0+C-a/6
SFztW5)2D9=>3f?+%iX!Y.w>6B)UfwSd:E&#F5LnDUv52@:at2VIEY8r]YW[vz8v)4Fl5U3q8LY%{n/x5]mHxrs$hb{RH9EAm@teDRt34}4{/n81R2d(Rh
g<{kvFP.Ferp[y&A<Af^&9*>33q/k=>OsX*#gAKlz(R<(8F.JHF#nuu?&*TahNtHBub?Rp(CHAji8rfxsTY0*E!>ichUUe-NILIwgz:fLCz0lhnO{sYo-4
CjkKftrx&sPKky?cP*Q8!0JGt{G*z-TX{XAi67jBY0Frjw}Uoy(&@Zwq)k1N>=m:^7%HySGp#61@Z[S2uB1fXBH2oEQ[sI6hl9*B<A^K+&dITzX?2uj@8u
=o>sg*Dqc#-w?wEsYzUk@rD8IdG--:3#DM:VEnAGRzrvOcAXJ3D=QH9N?7t9}?k{U0mt>i=iiAk#lOb>:mKGbgI7evypkfj7l0I7H2Jt[Ba^B@2fKA/tMJ
KU!kCX>6]zu^ffqgLIGMhP7^iF[q*lS7J]zHh@Y-tVTUdoQagyhe]gA)3G5P]UH.5m+<vh8e0R21Z?zU.iN}G6YiNWvc20PHqMhrx0CLvg25=Q6k^)+du?
oCrpy9sxwU[QMFf}c}nk*4xo<-by8X3.aHKjmO6c7IrGa5:SycZypWzbf6=09s/0r)00$cg!/MSwTGDQ<hi4aBkRPA[q#[gFGIb(V.qT:Jx}}&B-/idi2!
n*]+#}TZ{-wJcfESUCenI1&ffTi]P>+U=cS(fVUh=s=-=IL97Bi{}WP*Tu:-mcJ=G02FcyV?I5m}577mN8fr})8g1/@wNr8J%aQ[M2pe7P%u/Y>^8-PCeI
CyVZ%MTJ]5^L-G9^Bwxh1rg(uuge{6UOiHHi*rD[]F[KW?h9Mh1H=yKz0l*id*+P7.4AvpP[5U{F)#[xb}1!c]<v{x0R+1*^[<a{dncUyFcRLq3u-}}^ga
+s1sW=2ap>p3<3OKf(ypaBJ!b^DXwf1vy7@fj5nc2my7)R(2()!8RV91h@CF]?uz]wI!$6K68Y$bv:!tJ8rCcdK2$ADKFWQADBu=F$G3]lT?v$#OPh-hmX
u9HLh{wI>K#RAO1J-vQq}r^q!A6[i{-S{rHLF!MHOo>yGGYf?>3Om[*F++TDPPJG(5}&DCmyfvOj)4R49W9A*T6}K!{V:j&qk*$Pguv%znO]/PJSEzA1v%
FnlxRwy4a[aFT(w0&eKw#Uj-.V!(D^Z({L?0etW[2p?.})eYz5Jg0ZH8ZzNQF?Jc^D=1x6T*VW@SU0(uHS*k-N}A)SYvm1?klvEd!Sg{2X)!fBZmV*!m}W
4o3+K5Dz[yh$k?CnG=L:k=+L{lb94
]=];
db_music_file = [[
v{A#6<nsvra]<0X-FNxU6}o>eNez*!Q6I%AK>1bj6XL&#G7$<j4p!)W2W.gIaLvgwFb/MH3
]];
db_music_name = [[
JNf?4*DVQavCE]7kI$YtqYP2NL^>?lMTUO4^nFs?S.]KSF>u?jaS-IrN)@wQhfwt^q6={-ha]8=U%{qGzoV2)>:=o?JNKccj[0!.9%/4zX+D0w:E5Ng.vY
$eUkje$Jm/Uf]19@:{yB@8Jt).k/vdILPm$dH9EE+fw/{Mr6RU5^JnEakN:8K{I$DVb?5J#1wu1wwgUCvI/!{yNfiKl2ql=U!A3F1UTMr&@lE@D@[Mt{Um
4zGndiy-qM>SsHWa.R9c7YMa&fLmRd1{:vPnsp!J$AwA@Nt<RGkRf1C+^aePQm5uaQqoEtGO.fhhqvV&uUh=[uumOrX2xOH3iQa@.^JOt&Bj>2cTQqdMJu
!e*gKS7q]Iq=<E&)vS5FJc:==rmXGM&HibX&n[8VJVb[/d}:pl49QD?yqo?sNf3PRAvYH@psEftfMdjIkGA9?F/5py*?{IKUHa[cfa3sX7).Tfz/XKy=6K
Yam@>yUz81}$Rsndw#w0>55?m#(b@Oqm5)M4&AeJxNo?%Wfq1
]];
db_music_nkey = [[
rGpF{.YPww8931hrhGj(b)rD&C9d]wp<Je6=$:siJL>C++JenykhL4T09H{t.RCUI-lsy-Dfl&h>Zl#yF=Lo@/rH)<GU3{^VxAzrJmhZ(/j$Y%KxP8:FSG
D..H]%&ZTTcogI:818h>Gk)![V-O}3+u1
]];
db_music_strings = [[
Eogon&Y4B*opVRn0*CQlChXhiYpx#KOZn.g=zO!gG-G/*FLc4M]xBO!OrhayZkp@NLk/<jer.fxYpfeZG-yTM{p6]zBZ)7Z56PK{.GCK>NlD:qI})3Mh7#
[QG!4%sIH]B/u%Z{Lf:!!nTTlD]E>uTy7oS6!+=j-hId41lcDp#YB7dnjWqpSbsNoh#3d(uGeTjydoh<-Id=L%5a#L>tw#4u1SW}rJ7dq3-TE6*opoWy7m
y9]rb?TEN2nY){Xqqf5ax{k-=rAsH=!=voTt:1tF}QE?.ygA1KoI![wjH}VDH1o$Io?>pk#:$5/PaZ@g+bfH:?i*.PHW#&tT!hpBRXqf-lx$2.xbMA{F8O
84Nm5#z0-*Snec2#<TKbdSy=zQx)&SBW>l4pnQA}X]r#/zfpF[:R2$Avz59:/p1P>3Cu5>Q}3)U]cAd7]d^v{?6S!q:zlf^8ooKhFZ[&I*TGaF8=ms*-MS
d/xDQkEbydyL2W8/7rY9IOm/DLH9PPvWjqs]4k!Zt&Q4QMT@[rq4-!>8PwX>cd)t>38B*M]A-Zv9br!RkCyQn[Kk9E1Tbexh:5@KIKKYlK6@rsduta2ad9
VuflXC(}pc<Y5{l.RB#ZvWsf%oill^*X]X?4%6b=.EVTj3oZLg]Lz%Bh7yuviu@4X5kaQkV#1fVK>9^holvNzxJ2k&K+/oW]O9UH6a@})nh%Lz2Vt{RpT/
{#EHAO+yB&)7ah%Edj(G!9lh%quB{K=R]wiqYkA%]XPf)9e]6zm!iTTaBiEMqI8hk>6Pfhlc.0[SXhGOc^n6*c/5SW9ut9.5zfvf8v9n$me40PRs3/wEjQ
c<-bcv^{yr9Re$.]%M&(blC*wse?CRW@/Km&oy7Qs{>=h8zd5yrK+*w2?q:Kl@cf-<k.ffvn2G}x-5ym:u+KPVDkD-)ju0&Lgv].)vdru&w!}wFMS%h=4=
P@2JYO9M4!e17T!7Nk[oa>Lh2wtrgHSORc:AX+pk+.zxWJf=pIH.4C!-FUK(y@+xpS]m[-XM<?eohx{7C9$Kf:GtY]x**ZY%8&2pvBcKPsw8ZsFYy9<.wx
E=Lpgi-[al]0}?+]AvU}N5vZx9/<&f:0&AwO4(jc1<K[&)eT@O*k{cSU^Jb/(^yaD]czoBq7YC}4a$BgQ]mAHGWHExj2c4KzUv4XOuv2[ea8i%etm+%V}R
>cyRA:9!TNbGMXb+%JixolQ]e+pVD2d@?sq7[@V2QaW64VNJW#mR0L@F6!Z#Mn@YFQN0]Ny29A6bL4kyv//DXjAR7p*+H31bkHec?E?ls9qfhr)[+L#!uP
AcHGZ6H!/oDTg4U{/0Ht>E@bf?d^:F-9>k>iW4DeS]>p5Z%?b%46-9Jj#sd6.8n>}AksqcuBl0a!JwF/V62RX!v^r=Ov2HR@tKDZOK:s)WIZyi5ay)Wf#C
+HQt]xACCl*1C.AkQAhdA]Sr}rPujUM1O/[0CeU(cR&Lpu>CRak6X7da}6WhHtkHQm0xHd.0o(n]fjhkwTtec#B9t1PhB#Dd&M[87^>-biJ4=)0P7rxdP[
KP:#XJ?PjB+gPe(v6Ng=]Y^On/K{4Q*kW7G8}anB/]Axgd^tEV:(erD:akD[*33H9AhOmNxMDj}xEl#4m/xoS^pQZf^Vou}ry}T[haEWNxp=..Cql](k4v
6r2<ZeuKn2s7MxEFQ]pbhTyCPrQKib*APd5$-dSzTZE081*VZ@BSFyX3P%@%-}x0D6:fJrVSmxcSn:yOudmNKvW+Bw8Jln}7iPY#}uJ?$L6w-W<[ia@.lK
]FYTW+VGy!7oX[T4l0CFdxWJ@<s=G7O3Um!anDoWloxCo>U-5o(]OBn/*&o)cv8k=I8I+IK+MNGgP=b>VX=gBe?s]P1g]$-Lj]PW3BX[*V#OLV)K4tzsZ#
!S5ZCD+=/Yc6npzRs.Sc:k=DbxTQJ[O@(sc(9K=Ac%gT.XbICQP&AEa.n1<=/^JU}l1<[1KP)xhS7s7*T>2y-}]4TIv8rY=[w@<>c4Urai^iijOk9Sc]Yu
3iP7u4FEfeo)z+2t8tB@HRcTco-*rgOyHZ<5V.m&G*98[Jr(>&=iBmU1$OQ^x?KmtW&Axs(^<PCqBM8)04D4?Y^Gr]K/ia@5>m::To:e?Q$iagT+v}4.iY
?b04>A]@@jcjMJEcM]7mQ[ToiW4E{P1TCGY*[o*AQ58Y*h]Yzx8W]GN4%1$xJ>:T[Vub:8P}BU^cm}z-sXWGO!o%ec&DqpSn6:n@/ye.j#7su#[=XK+j}z
lJaI2NvZ/5G-8C[CE>ljHR8sf5/t](]-Yr*kbQ3g==$]T]$}VqYlz0?60!BGywMjm.wr!w%r[i-:aUs2DBhv/ULycDDxWJuS>oez5w&UvIo-Fa4uolzT-E
P].f]lN[=s>>}-2p05E}XRA-sNrh+Stcq6v4CDsJL{{z}G@Qk2P{H&[z6:XP::cnADu2lNo{#/@VS}:E2P26LGEr8=@@r303
]];
db_music_time = [[
1WC{Q69e}ZfYNT1{tbc77mOK(x0Zbp:#LqfgLht<m:2mTeZ#88J+D0!GTWK9mX(XiIO$r&K+0!=k%wK:haTEd>-RQL2M{=>)4DYG7yOBuX}Q4^1+>2t+)&
T5)@4x3F+UeMiFrPs[#MMav3unUeOrYr.eGnU}W^[*WoBw-f?pQQ<]UjxAv.DmNnd1L/?@Kyjh-+)o9=n7:SLV^SK-mKT2MB$5vh/d?G20p[X$jYauTPnq
a^E$XLl^g:!/KX69EmjE0lCF)dgIIf9*1)<:kIG3h>!SOuz+]zY%s&M&?rwdL=NA<I4ep688<xQZ<9Y-PH^ER5?U%-^2hBnUFZSwl8#>gHA<$iC1qgrQlF
/q)v5Q4leGJ:L9?.!0-$OzHbTeyodcFuLB$1*A%gNW=bvs&J1M5sD/6SMM*6xD8sf)1n3h669Z$-59iLwZ7f5fNwN!v9#*3UudCqWz&z5eKIZ8hHtw9Fn/
M=W@(9E)EPxC-O6/-vFRSk[*vCOj2qeK98R^NHOY9z6xPVNaj%P2hsIIMMZhuT(?JI[.x2#L$oe!aiB$nj:Cu0(^>AOg88G!prz37?NX<4]fi?vw7MyRH:
@@r303
]];
