-- THIS FILE IS AUTOMATICALLY GENERATED.
--
-- Changes to this file will be discarded, ignored, and every other negative
-- word you can come up with that has the same overall meaning.
--
-- This file is licensed under the terms expressed in the LICENSE file.
local version = select(4, GetBuildInfo());
if --[[@ WriteVersionConstraint("version") @]] then
    return;
end

local LibStub = assert(LibStub, "Missing dependency: LibStub");
local LibRPMedia = LibStub:GetLibrary("LibRPMedia-1.0");

LibRPMedia:RegisterDatabase("music", {
    size = --[[@ WriteValue(music.size) @]],
    data = --[[@ WriteValue(music.data) @]],
    tree = --[[@ WriteValue(music.tree) @]],
});
