-- THIS FILE IS AUTOMATICALLY GENERATED.
--
-- Changes to this file will be discarded, ignored, and every other negative
-- word you can come up with that has the same overall meaning.
--
-- This file is licensed under the terms expressed in the LICENSE file.
--
-- Client Version: [[@ build.version @]]
-- Build Config: [[@ build.bkey @]]

if LE_EXPANSION_LEVEL_CURRENT ~= [[@ expansion @]] then
    return;
end

local LRPM12 = LibStub and LibStub:GetLibrary("LibRPMedia-1.2", true);

if not LRPM12 or LRPM12.db ~= nil then
    return;
end

local db_icons_id;
local db_icons_name;
local db_music_file;
local db_music_name;
local db_music_nkey;
local db_music_time;

local function RegisterDatabase()
    LRPM12.db = {
        icons = {
            size = [[@ db.icons.size @]],
            id   = db_icons_id,
            name = db_icons_name,
        },
        music = {
            size = [[@ db.music.size @]],
            file = db_music_file,
            name = db_music_name,
            nkey = db_music_nkey,
            time = db_music_time,
        },
    };
end

db_icons_id = [[@ db.icons.id @]];
db_icons_name = [[@ db.icons.name @]];
db_music_file = [[@ db.music.file @]];
db_music_name = [[@ db.music.name @]];
db_music_nkey = [[@ db.music.nkey @]];
db_music_time = [[@ db.music.time @]];

RegisterDatabase();
