-- THIS FILE IS AUTOMATICALLY GENERATED.
--
-- Changes to this file will be discarded, ignored, and every other negative
-- word you can come up with that has the same overall meaning.
--
-- This file is licensed under the terms expressed in the LICENSE file.
--
-- Client Version: <%- build.version %>
-- Build Config: <%- build.bkey %>
if WOW_PROJECT_ID ~= <%- config.project %> then
    return;
end

local LibRPMedia = LibStub and LibStub:GetLibrary("LibRPMedia-1.0", true);
if not LibRPMedia then
    return;
end

if not LibRPMedia:IsDatabaseRegistered("icons") then
    LibRPMedia:RegisterDatabase("icons", <%- Dump(database.icons, { indentDepth = 1 }) %>);
end

if not LibRPMedia:IsDatabaseRegistered("music") then
    LibRPMedia:RegisterDatabase("music", <%- Dump(database.music, { indentDepth = 1 }) %>);
end
